spring.application.name=sagefolio
server.port=8080

# H2 In-Memory Database
spring.datasource.url=jdbc:h2:mem:sagefoliodb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

# Gemini API Key (free — get at aistudio.google.com)
gemini.api.key="ENTER API KEY"

# Caffeine cache — stock data for 15 minutes
spring.cache.type=caffeine
# gainersCache expires after 24 hours (1440 minutes) — refreshes once per day
spring.cache.cache-names=stockCache,gainersCache
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=15m

# Alpha Vantage API Key
alphavantage.api.key="ENTER API KEY"

# Logging
logging.level.com.sagefolio=DEBUG
